# Generated by Django 2.2.3 on 2019-07-15 06:58

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=32, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='邮箱地址')),
                ('sex', models.BooleanField(default=None, verbose_name='性别')),
                ('icon', models.ImageField(default='blog/img/default/icon.png', upload_to=myblog.models.user_avatar_path, verbose_name='头像')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否禁用')),
                ('is_activate', models.BooleanField(default=False, verbose_name='是否激活')),
                ('ticket', models.CharField(max_length=30, null=True, verbose_name='session值')),
                ('logintime', models.DateTimeField(auto_now=True, verbose_name='最近登录')),
                ('registertime', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('phonenumber', models.CharField(default='0', max_length=62, verbose_name='手机号码')),
                ('reserve2', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve3', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve4', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve5', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve6', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve7', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
            ],
        ),
    ]
