# Generated by Django 2.2.3 on 2019-07-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190715_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='icon',
            field=models.ImageField(default='myblog/img/user/icon.png', upload_to='', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('picture', models.ImageField(default='myblog/img/user/icon.png', upload_to='', verbose_name='图片')),
                ('first_classify', models.IntegerField(max_length=4, verbose_name='一级分类')),
                ('second_classify', models.IntegerField(max_length=4, verbose_name='二级分类')),
                ('third_classify', models.IntegerField(max_length=4, verbose_name='三级分类')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('alterdate', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('praise', models.IntegerField(default=0, verbose_name='点赞')),
                ('share', models.IntegerField(default=0, verbose_name='分享')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否显示')),
                ('reserve1', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve2', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve3', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve4', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve5', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.UserModel', verbose_name='作者')),
            ],
        ),
    ]
