# Generated by Django 2.2.3 on 2019-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190715_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='first_classify',
            field=models.IntegerField(verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='second_classify',
            field=models.IntegerField(verbose_name='二级分类'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='third_classify',
            field=models.IntegerField(verbose_name='三级分类'),
        ),
    ]
